name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
# TODO maybe change rust-cache to normal version like rust-cache@2 or something
jobs:
  coverage:
    name: Build & Collect test coverage
    runs-on: windows-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: llvm-tools-preview
          target: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc
      - name: Collect coverage data
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: nextest --target x86_64-pc-windows-msvc
      - name: Zip files
        uses: vimtor/action-zip@v1
        with:
          files: target\x86_64-pc-windows-msvc\release\reframework-updater.exe
          dest: refresher.zip
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release        
      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v3
      #   with:
      #       semantic_version: 17.1.1
      #       extra_plugins: |
      #           @semantic-release/commit-analyzer
      #           @semantic-release/release-notes-generator
      #           @semantic-release/github
      #           @semantic-release/git

      #   env:
      #       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}