name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

# jobs:
#   build_and_test:
#     name: Rust project
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           override: true
#           target: x86_64-pc-windows-msvc
#       - uses: actions-rs/cargo@v1
#         with:
#           command: nextest
#           args: run --profile ci
#       - uses: actions-rs/cargo@v1
#         with:
#           command: build
#           args: --release
# jobs:
#   build-test-artifacts:
#     name: Build test artifacts
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           # By default actions/checkout checks out a merge commit. Check out the PR head instead.
#           # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
#           ref: ${{ github.event.pull_request.head.sha }}
#       - uses: actions-rs/toolchain@v1
#         with:
#           toolchain: stable
#           override: true
#       - name: Install nextest
#         uses: taiki-e/install-action@nextest
#       - name: Build and archive tests
#         run: cargo nextest archive --archive-file nextest-archive.tar.zst
#       - name: Upload archive to workflow
#         uses: actions/upload-artifact@v3
#         with:
#           name: nextest-archive
#           path: nextest-archive.tar.zst

#   run-tests-partitioned:
#     name: Run tests with partitioning
#     runs-on: ubuntu-latest
#     needs: build-test-artifacts
#     strategy:
#       matrix:
#         partition: [1, 2]
#     steps:
#       # The source directory must be checked out.
#       - uses: actions/checkout@v2
#         with:
#           # By default actions/checkout checks out a merge commit. Check out the PR head instead.
#           # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
#           ref: ${{ github.event.pull_request.head.sha }}
#       # In this example, the Rust toolchain is not installed. cargo nextest's run phase does not
#       # require Cargo. You can choose to install Rust if your tests require it, of course.
#       # Instead, create ~/.cargo/bin as required by the install action.
#       - run: mkdir -p ~/.cargo/bin
#       - name: Install nextest
#         uses: taiki-e/install-action@nextest
#       - name: Download archive
#         uses: actions/download-artifact@v3
#         with:
#           name: nextest-archive
#       - name: Run tests
#         run: |
#           ~/.cargo/bin/cargo-nextest nextest run --archive-file nextest-archive.tar.zst \
#             --partition count:${{ matrix.partition }}/2


jobs:
  coverage:
    name: Build & Collect test coverage
    runs-on: windows-latest
    # nightly rust might break from time to time
    continue-on-error: true
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: llvm-tools-preview
          target: x86_64-pc-windows-msvc
      - uses: Swatinem/rust-cache@c5ed9ba6b7e1bb8aff90d43acd2f0af4990fa57c
      
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc
      - name: Collect coverage data
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: nextest --target x86_64-pc-windows-msvc